### ISSUE TITLE
Migrate to Datafaker?

### ISSUE THREAD

**Issue by bodiam** [knaufk/flink-faker#27]
Hi there, my name is Erik Pragt, and sorry for the plug, but I'm one of the authors of Datafaker (https://www.datafaker.net), and I was wondering if you'd be willing to consider to migrate to datafaker.net instead of javafaker.

Datafaker is a fork of Javafaker, but it's a bit more modern (Java 8/11), almost zero dependencies (since 1.1.0), has a lot of new data providers, quite a few issues fixed, and I'm planning on making a release ~every month. I've created Datafaker mostly because of the lack of releases of Javafaker and their inactivity on open PRs, which is something which I'm hoping to do better for Datafaker. 

Datafaker is mostly a drop in replacement of Javafaker, so migrating should be low effort, but I'm willing to submit a PR if you are open to the idea of a migration, but no worries if not! Cheers, Erik

**Comment by knaufk** [comment]
Hi Eric, 

thank your for reaching out. Are all Java Faker expressions compatible with Data Faker or would we risk breaking existing sources/sinks with the swich?

**Comment by bodiam** [comment]
Hi @knaufk , it's 100% compatible, but I changed the imports to `net.datafaker`, but functionality wise, it's identical, but it has quite a few bugs fixed. I'm planning on releasing a new version (1.1.0) of Datafaker in 9 days.

**Comment by bodiam** [comment]
@knaufk recently, Vividus also migrated (https://github.com/vividus-framework/vividus/pull/2368/files), the change was minimal.

**Comment by bodiam** [comment]
Hi @knaufk , just wanted to let you know I just released Datafaker 1.1.0. https://jworks.io/datafaker-1-1-0-released/

**Comment by knaufk** [comment]
Done. I think this justifies a new minor version. Thanks for the pointer.
