### ISSUE TITLE
Support More Complex Data Types  

### ISSUE THREAD

**Issue by knaufk** [knaufk/flink-faker#4]
Support for ``ROW``, ``MAP``, ``ÀRRAY`` and ``MULTISET``

**Comment by anora10** [comment]
I am working on a solution that supports ARRAY, ROW and MAP data types. For arrays and maps may be generated with a query specifying size and expression types (i.e. superhero name). For a row, the row fields can be specified in the query. The current prototype still needs a few fixes, but I will finish it soon.

**Comment by anora10** [comment]
I am working on a solution that supports ARRAY, ROW and MAP data types. I will open a PR soon.
