### ISSUE TITLE
why  ~ in the end?Thanks

### ISSUE THREAD

**Issue by appleyuchi** [knaufk/flink-faker#7]
A newbie question.

why there's a `~` in the end of thd `id` produced by faker?

````
CREATE TABLE subscriptions ( 
    id STRING,
    user_id INT,
    type STRING,
    start_date TIMESTAMP(3),
    end_date TIMESTAMP(3),
    payment_expiration TIMESTAMP(3),
    proc_time AS PROCTIME()
) WITH (
  'connector' = 'faker',
  'fields.id.expression' = '#{Internet.uuid}', 
  'fields.user_id.expression' = '#{number.numberBetween ''1'',''50''}',
  'fields.type.expression'= '#{regexify ''(basic|premium|platinum){1}''}',
  'fields.start_date.expression' = '#{date.past ''30'',''DAYS''}',
  'fields.end_date.expression' = '#{date.future ''365'',''DAYS''}',
  'fields.payment_expiration.expression' = '#{date.future ''365'',''DAYS''}'
);
````

![這麼多的票號](https://user-images.githubusercontent.com/27613483/106622613-bb898980-65ae-11eb-972b-8c42d19e2429.png)

**Comment by knaufk** [comment]
This seems to be SQL Clients's ellippsis icon. If I run it in Ververica Platform you can see it looks "normal". 

![2021-02-02_16-59](https://user-images.githubusercontent.com/11538663/106626469-0936cf80-6578-11eb-9631-
43be36f80f4b.png)

**Comment by appleyuchi** [comment]
Thanks for your reply.

you said "looks"
what's its real value?
contains `~` or NOT
Thanks for your help.

**Comment by knaufk** [comment]
The real value is not shown, because the column is too long. The missing characters are replaced by ~.

**Comment by appleyuchi** [comment]
got it,
Thanks~!
